### ISSUE TITLE
Richtext bracket syntax

### ISSUE THREAD

**Issue by Indy79** [Tolc/IntelliJ_Jahia_plugin#11]
Hi,

It would be great, if you can handle this kind of syntax in "richtext" bracket.

I get an syntax error with : `- test (string, richtext[ckeditor.customConfig='$context/modules/test-jahia7-template/javascript/test/ckeditor/ckconfig_basic.js']) mandatory`

thank guy ! keep it up ! :+1:

**Comment by Tolc** [comment]
Hello !

Actually I've just stumbled upon that issue a couple of minutes ago an I've fixed it in commit https://github.com/Tolc/IntelliJ_Jahia_plugin/commit/2f8bd208e96f9e1c830ca03c334bef1fe2d0586a

Sorry about this problem, plugin won't work properly for all the nodetypes in the same cnd file after the one having this property, because it is grammar breaking :/

Will be fixed in version 1.1, which will be ready at the end of the week I think.
