### ISSUE TITLE
Typo in autocomplete

### ISSUE THREAD

**Issue by cbrandes** [Tolc/IntelliJ_Jahia_plugin#19]
When using autocomplete feature, there is no "mandatory" propostition but a "madatory" one. Jahia doesn't like this propostion.

**Comment by Tolc** [comment]
Damn! So sorry!
Weird I haven't stumbled upon that in the previous weeks myself. At least the validation does highlight it as an invalid attribute.
Will be corrected in next version (1.2.1, out at the end of the week). 

Thank you for reporting it! :)

PS: Were you previously working at Smile and have a 'Viking' look? Because your name seems really familiar!

**Comment by cbrandes** [comment]
Yep, same one, was at the meetup yesterday.

**Comment by Tolc** [comment]
J'ai travaillé chez Smile Lille pendant 3 ans sur du Jahia 6.1 et 6.6 quand tu y étais encore et je me rappelle que tu m'as aidé sur du support Jahia à l'époque. Marrant qu'on se retrouve ici ! Et content de voir que mon plugin sert à quelque chose.

En tout cas merci d'avoir ouvert une issue, et n'hésite pas si tu en vois d'autres !
