### ISSUE TITLE
Make project structure more understandable

### ISSUE THREAD

**Issue by artyom-88** [Tolc/IntelliJ_Jahia_plugin#23]
Current project structure is too difficult and doesn't satisfy some Java standards

**Comment by Tolc** [comment]
Well, tell JetBrains then. It is based on their tutorial project.

I accept constructive pull-requests btw ;)

**Comment by artyom-88** [comment]
What about "gen" folder?

**Comment by artyom-88** [comment]
And you have duplicates META-INF folders with plugin.xml (project root and resources)

**Comment by Tolc** [comment]
"gen" folder is for grammar and parsing classes generated by GrammarKit and JFlex. Again, it comes from JetBrains tutorial project.
See https://github.com/JetBrains/intellij-sdk-docs/tree/master/code_samples/simple_language_plugin and http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html
It is not the most elegant way, but it makes sense.

As for the duplication of the META-INF folder, the reason is simple: I've noticed that one was required for my plugin to be recognized by IntelliJ versions < 15, and the other for versions >= 15 (don't remember which though). I don't like it neither.

**Comment by artyom-88** [comment]
Ok
