### ISSUE TITLE
definitions.cnd reference with jahia native CND

### ISSUE THREAD

**Issue by totohh-zz** [Tolc/IntelliJ_Jahia_plugin#42]
Hello,
I installed this plugin.
I don't understand why Intellij doesn't find reference to native node and property.
For instance :
- jcr:title => title is detected as unresolved symbol in JSP file
- [mynt:customNode] > jnt:content => content is detected ad unresolded CND node type in my CND file
Many thanks,
Thomas

**Comment by Tolc** [comment]
Hello @totohh, and thanks for the feedback!

- The properties references are - for now - only available in properties files, not in JSP/XML/Java/... I'm currently actively working on that. IntelliJ marks 'jcr:title' as unresolved because it believes it is a nodetype. Both those issues will be fixed when I'm done with the properties references/completions, next release I hope ;)
- A restart of the project is needed for the base CND files to be correctly loaded by IntelliJ the first time you open a project. I've recently fixed this in 86eed03188dc459d9f183b5d0e3dfaba78938d12, so this initial restart won't be necessary anymore in the next release.

Hope it helps
