### ISSUE TITLE
CND: Invalid property default value multiple

### ISSUE THREAD

**Issue by totohh-zz** [Tolc/IntelliJ_Jahia_plugin#51]
Hello,
I have a problem with the plugin when it parses my definitions.cnd with a property multiple which have 2 default values :
[mynt:socialsharing] > jnt:content, jmix:socialComponent
 - socialNetworks (string, choicelist[resourceBundle]) = 'facebook', 'google' multiple indexed=no < 'facebook', 'google', 'twitter', 'linkedin', 'viadeo'

So, the other components and their views are not visible.

Best regards,
Thomas

**Comment by Tolc** [comment]
Hello and sorry for the little delay,
You're right, there is an issue with multiple default values, mainly because....well, I actually never had to do that in a project, so I just had no idea it was possible until now. So thanks I guess 😄

I'm working on a quick fix for it and I'll release it as soon as possible.
In the meantime, I suggest you put this nodetype definition at the end of your cnd file so the rest of the file is properly parsed...

**Comment by Tolc** [comment]
I've just released v2.0.1 (which was long overdue anyway), so after the plugin update you should not have this issue anymore. Peace!
