### ISSUE TITLE
Intellij is freezing on definition.cnd 

### ISSUE THREAD

**Issue by stephjour** [Tolc/IntelliJ_Jahia_plugin#68]
In IntelliJ IDEA 2022.3 (Ultimate Edition) Build #IU-223.7571.182 when definition.cnd is open, intellij is freezing and has trouble to update the ui with jahia pluggin v2.1.1
Content is not updated when scrolling and clicking on the edit window make some part of the file updated.
Passing the first 100 lignes restore the behavior.
My definition.cnd has currently more then 700 ligne of definition.
Disable the pluggin restore intellij behavior to normal.

**Comment by Tolc** [comment]
Hello there,

I can't reproduce any kind of freeze and my cnd file has more than 1600 lines, so that's likely not the issue.

Maybe some grammar that's not properly recognized?
You could try to separate you cnd into smaller cnd files, or just remove parts of its content using some kind of dichotomy logic until finding out what's causing this.
Did you also try with an empty (or almost empty) cnd file?
